name: 'CI'

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        lisp:
          - sbcl-bin
          - ccl-bin

    env:
      LISP: ${{ matrix.lisp }}
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: 40ants/setup-lisp@v4
        with:
          asdf-system: puzzles
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: puzzles
          coveralls-token: |
            ${{ matrix.lisp == 'sbcl-bin' &&
                matrix.os == 'ubuntu-latest' &&
                secrets.github_token }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: /tmp/*/*.html
